baseURL = "https://meik2333.com/"
languageCode = "zh-cn"
title = "Hansomxue99's blog"
theme = "github-style-master"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hansomxue99"
  description = "In solitude, where we are least alone."
  rss = false
  github = "https://github.com/hansomxue99"
  csdn = "https://blog.csdn.net/weixin_46185572"
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "China"
  enableGitalk = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]